# tests/integration/remi/containers/Containerfile.opensuse-tumbleweed
# Authentic openSUSE Tumbleweed rolling container for package acceptance.

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG INSTALL_MODE=binary

RUN sed -i \
        's#^baseurl=http://download.opensuse.org/tumbleweed/repo/non-oss/$#baseurl=https://downloadcontent.opensuse.org/history/20260908/tumbleweed/repo/non-oss/#' \
        /etc/zypp/repos.d/repo-non-oss.repo \
    && sed -i \
        's#^baseurl=http://download.opensuse.org/tumbleweed/repo/oss/$#baseurl=https://downloadcontent.opensuse.org/history/20260908/tumbleweed/repo/oss/#' \
        /etc/zypp/repos.d/repo-oss.repo \
    && sed -i 's/^enabled=1$/enabled=0/' \
        /etc/zypp/repos.d/repo-openh264.repo \
        /etc/zypp/repos.d/repo-update.repo \
    && grep -Fx \
        'baseurl=https://downloadcontent.opensuse.org/history/20260908/tumbleweed/repo/non-oss/' \
        /etc/zypp/repos.d/repo-non-oss.repo \
    && grep -Fx \
        'baseurl=https://downloadcontent.opensuse.org/history/20260908/tumbleweed/repo/oss/' \
        /etc/zypp/repos.d/repo-oss.repo \
    && grep -Fx 'enabled=0' /etc/zypp/repos.d/repo-openh264.repo \
    && grep -Fx 'enabled=0' /etc/zypp/repos.d/repo-update.repo \
    && zypper --non-interactive install --no-recommends \
        ca-certificates \
        diffutils \
        findutils \
        gawk \
        libseccomp2 \
        python3 \
        shadow \
        sqlite3 \
    && zypper clean --all

COPY conary* /tmp/install/

RUN if [ "$INSTALL_MODE" = "package" ] && [ -f /tmp/install/conary-release.rpm ]; then \
        zypper --non-interactive install --allow-unsigned-rpm /tmp/install/conary-release.rpm; \
    elif [ -f /tmp/install/conary ]; then \
        install -m 755 /tmp/install/conary /usr/bin/conary; \
    else \
        echo "No conary binary or package found in build context" >&2; exit 1; \
    fi && rm -rf /tmp/install

RUN /usr/bin/conary --version \
    && command -v awk \
    && command -v cmp \
    && command -v diff \
    && command -v find \
    && command -v gpg \
    && command -v python3 \
    && command -v setsid \
    && test -e /lib64/ld-linux-x86-64.so.2

COPY config.toml /opt/remi-tests/config.toml
COPY fixtures/ /opt/remi-tests/fixtures/

RUN mkdir -p /var/lib/conary /results

ENV DISTRO=opensuse-tumbleweed
ENV DB_PATH=/var/lib/conary/conary.db
ENV RESULTS_DIR=/results
ENV CONARY_BIN=/usr/bin/conary

CMD ["sleep", "infinity"]
