// apps/conary/tests/packaging_m3c.rs

#![cfg(test)]
#![cfg(feature = "test-hooks")]

pub mod common;

use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Output, Stdio};

use conary_core::ccs::SigningKeyPair;
use conary_core::db::models::{TrySession, TrySessionStatus};
use conary_core::runtime_root::ConaryRuntimeRoot;

struct WatchFixture {
    _work: tempfile::TempDir,
    source: PathBuf,
    source_cache: PathBuf,
    signing_key: PathBuf,
    db_path: String,
    _db_temp: tempfile::TempDir,
}

impl WatchFixture {
    fn new() -> Self {
        let work = tempfile::tempdir().unwrap();
        let root = work.path().to_path_buf();
        let source = root.join("source");
        let source_cache = root.join("source-cache");
        let signing_key = root.join("try-watch.private");
        SigningKeyPair::generate()
            .with_key_id("try-watch-test")
            .save_to_files(&signing_key, &root.join("try-watch.public"))
            .unwrap();
        write_watch_project(&source, "hello-one");
        let (db_temp, db_path) = common::setup_command_test_db();
        create_current_generation(&db_path);
        Self {
            _work: work,
            source,
            source_cache,
            signing_key,
            db_path,
            _db_temp: db_temp,
        }
    }
}

fn write_watch_project(source: &Path, message: &str) {
    fs::create_dir_all(source.join("src")).unwrap();
    fs::write(
        source.join("Cargo.toml"),
        r#"[package]
name = "watch-demo"
version = "0.1.0"
edition = "2021"
"#,
    )
    .unwrap();
    fs::write(
        source.join("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "watch-demo"
version = "0.1.0"
"#,
    )
    .unwrap();
    fs::write(
        source.join("recipe.toml"),
        r#"[package]
name = "watch-demo"
version = "0.1.0"

[source]
path = "."

[build]
install = "cargo build --quiet && mkdir -p %(destdir)s/usr/bin && cp target/debug/watch-demo %(destdir)s/usr/bin/watch-demo"
"#,
    )
    .unwrap();
    fs::write(
        source.join("src/main.rs"),
        format!("fn main() {{ println!(\"{message}\"); }}\n"),
    )
    .unwrap();
}

fn base_watch_command(fixture: &WatchFixture) -> Command {
    let mut command = Command::new(env!("CARGO_BIN_EXE_conary"));
    command
        .env("CONARY_TEST_SKIP_GENERATION_MOUNT", "1")
        .env("CONARY_TEST_TRY_LAUNCHER", "echo")
        .env("CONARY_TRY_WATCH_SOURCE_CACHE", &fixture.source_cache)
        .args(["try", "--watch"])
        .arg(&fixture.source)
        .arg("--key")
        .arg(&fixture.signing_key)
        .args(["--db-path", &fixture.db_path]);
    command
}

fn watch_until_test_exit(fixture: &WatchFixture, json: bool) -> Output {
    let mut command = base_watch_command(fixture);
    command.env("CONARY_TEST_TRY_WATCH_EXIT_AFTER_READY", "1");
    if json {
        command.arg("--json");
    }
    command.output().expect("failed to run conary try --watch")
}

fn spawn_watch(
    fixture: &WatchFixture,
    ready_file: &Path,
    failure_file: Option<&Path>,
    json: bool,
    extra_env: &[(&str, &str)],
) -> Child {
    let mut command = base_watch_command(fixture);
    command
        .env("CONARY_TEST_TRY_WATCH_READY_FILE", ready_file)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    if let Some(path) = failure_file {
        command.env("CONARY_TEST_TRY_WATCH_FAILURE_FILE", path);
    }
    if json {
        command.arg("--json");
    }
    for (key, value) in extra_env {
        command.env(key, value);
    }
    command.spawn().expect("failed to spawn conary try --watch")
}

fn wait_for_file_or_child_exit(path: &Path, child: &mut Child) {
    for _ in 0..100 {
        if path.exists() {
            return;
        }
        if let Some(status) = child.try_wait().expect("watch child status") {
            panic!(
                "watch exited before {} with {status}\n{}",
                path.display(),
                read_child_pipes(child)
            );
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
    let _ = child.kill();
    let status = child.wait().expect("watch child wait after kill");
    panic!(
        "timed out waiting for {} after {status}\n{}",
        path.display(),
        read_child_pipes(child)
    );
}

fn wait_for_generation_change_or_child_exit(
    db_path: &str,
    previous_generation: i64,
    child: &mut Child,
) -> i64 {
    for _ in 0..150 {
        if let Some(session) = active_try_session(db_path)
            && let Some(generation) = session.try_generation_id
            && generation != previous_generation
        {
            return generation;
        }
        if let Some(status) = child.try_wait().expect("watch child status") {
            panic!(
                "watch exited before generation changed with {status}\n{}",
                read_child_pipes(child)
            );
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
    let _ = child.kill();
    let status = child.wait().expect("watch child wait after kill");
    panic!(
        "timed out waiting for try generation change after {status}\n{}",
        read_child_pipes(child)
    );
}

fn read_child_pipes(child: &mut Child) -> String {
    let mut stdout = String::new();
    if let Some(mut pipe) = child.stdout.take() {
        let _ = pipe.read_to_string(&mut stdout);
    }
    let mut stderr = String::new();
    if let Some(mut pipe) = child.stderr.take() {
        let _ = pipe.read_to_string(&mut stderr);
    }
    format!("stdout:\n{stdout}\nstderr:\n{stderr}")
}

fn rollback(fixture: &WatchFixture) {
    let output = Command::new(env!("CARGO_BIN_EXE_conary"))
        .env("CONARY_TEST_SKIP_GENERATION_MOUNT", "1")
        .args(["try", "rollback", "--db-path", &fixture.db_path])
        .output()
        .expect("failed to run conary try rollback");
    assert_success(&output);
}

fn active_try_session(db_path: &str) -> Option<TrySession> {
    let conn = conary_core::db::open(db_path).unwrap();
    TrySession::find_active_or_orphaned(&conn).unwrap()
}

fn create_current_generation(db_path: &str) {
    let runtime_root = ConaryRuntimeRoot::from_db_path(PathBuf::from(db_path));
    let conn = conary_core::db::open(db_path).unwrap();
    conary_core::ccs::HostCapabilityInventory::default()
        .persist(&conn)
        .unwrap();
    let selected_root = tempfile::tempdir().unwrap();
    conary_core::generation::builder::materialize_selected_root_from_db(
        &conn,
        &runtime_root.objects_dir(),
        selected_root.path(),
    )
    .unwrap();
    let captured = conary_core::generation::root_manifest::scan_selected_root(
        selected_root.path(),
        &conary_core::filesystem::CasStore::new(runtime_root.objects_dir()).unwrap(),
    )
    .unwrap();
    let (generation, _) =
        conary_core::generation::builder::build_generation_from_captured_root_with_boot_root_and_activation(
            &conn,
            &runtime_root.generations_dir(),
            "packaging-m3c try-watch base",
            &conary_core::generation::builder::BootRoot::Staged(runtime_root.root().join("boot")),
            conary_core::generation::builder::GenerationActivation::Active,
            captured,
        )
        .unwrap();
    conary_core::generation::mount::update_current_symlink(runtime_root.root(), generation)
        .unwrap();
}

fn stdout_text(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn output_text(output: &Output) -> String {
    format!(
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

fn assert_success(output: &Output) {
    assert!(output.status.success(), "{}", output_text(output));
}

fn assert_failure(output: &Output) {
    assert!(!output.status.success(), "{}", output_text(output));
}

#[test]
fn try_watch_startup_creates_active_namespace_session_and_refuses_keep() {
    let fixture = WatchFixture::new();
    let ready = fixture.source.join(".watch-ready");

    let mut child = spawn_watch(&fixture, &ready, None, false, &[]);
    wait_for_file_or_child_exit(&ready, &mut child);

    let session = active_try_session(&fixture.db_path).expect("active watch session");
    assert_eq!(session.status, TrySessionStatus::Active);
    assert!(
        Path::new(&session.work_dir)
            .join(".conary-try-watch-session.json")
            .is_file()
    );

    let keep = Command::new(env!("CARGO_BIN_EXE_conary"))
        .env("CONARY_TEST_SKIP_GENERATION_MOUNT", "1")
        .args(["try", "keep", "--db-path", &fixture.db_path])
        .output()
        .expect("failed to run conary try keep");
    assert_failure(&keep);
    assert!(output_text(&keep).contains("watch-created try session"));

    child.kill().expect("kill watch process");
    let _ = child.wait();
    rollback(&fixture);
}

#[test]
fn try_watch_json_outputs_ndjson_without_human_stdout() {
    let fixture = WatchFixture::new();

    let output = watch_until_test_exit(&fixture, true);
    assert_success(&output);
    let stdout = stdout_text(&output);

    assert!(
        !String::from_utf8_lossy(&output.stderr).contains("Watching"),
        "{}",
        output_text(&output)
    );
    let mut last = None;
    for line in stdout.lines() {
        let value: serde_json::Value = serde_json::from_str(line)
            .unwrap_or_else(|error| panic!("bad NDJSON line {line:?}: {error}\n{stdout}"));
        assert_eq!(value["schema_version"], 1);
        assert!(
            value["operation_id"]
                .as_str()
                .unwrap()
                .starts_with("try-watch-")
        );
        assert!(value["sequence"].as_u64().unwrap() >= 1);
        last = Some(value);
    }
    let last = last.expect("expected at least one NDJSON event");
    assert_eq!(last["kind"], "operation-finished");
}

#[test]
fn try_watch_refuses_dirty_tracked_tree_in_ci() {
    let fixture = WatchFixture::new();
    Command::new("git")
        .args(["init"])
        .current_dir(&fixture.source)
        .status()
        .expect("git init")
        .success()
        .then_some(())
        .expect("git init should succeed");
    Command::new("git")
        .args(["config", "user.email", "conary@example.invalid"])
        .current_dir(&fixture.source)
        .status()
        .expect("git config email");
    Command::new("git")
        .args(["config", "user.name", "Conary Test"])
        .current_dir(&fixture.source)
        .status()
        .expect("git config name");
    Command::new("git")
        .args(["add", "."])
        .current_dir(&fixture.source)
        .status()
        .expect("git add");
    Command::new("git")
        .args(["commit", "-m", "initial"])
        .current_dir(&fixture.source)
        .status()
        .expect("git commit");
    fs::write(
        fixture.source.join("src/main.rs"),
        "fn main() { println!(\"dirty\"); }\n",
    )
    .unwrap();

    let output = base_watch_command(&fixture)
        .env("CI", "1")
        .output()
        .expect("failed to run conary try --watch");

    assert_failure(&output);
    assert!(
        output_text(&output).contains("dirty local tree"),
        "{}",
        output_text(&output)
    );
    assert!(active_try_session(&fixture.db_path).is_none());
}

#[test]
fn try_watch_failed_refresh_keeps_last_successful_generation() {
    let fixture = WatchFixture::new();
    let ready = fixture.source.join(".watch-ready");
    let failure = fixture.source.join(".watch-failure");

    let mut child = spawn_watch(&fixture, &ready, Some(&failure), false, &[]);
    wait_for_file_or_child_exit(&ready, &mut child);
    let session = active_try_session(&fixture.db_path).expect("active watch session");
    let first_generation = session.try_generation_id.expect("initial generation");

    fs::write(
        fixture.source.join("src/main.rs"),
        "fn main() { this is not rust }\n",
    )
    .unwrap();
    wait_for_file_or_child_exit(&failure, &mut child);

    let session = active_try_session(&fixture.db_path).expect("active watch session");
    assert_eq!(session.try_generation_id, Some(first_generation));

    child.kill().expect("kill watch process");
    let _ = child.wait();
    rollback(&fixture);
}

#[test]
fn try_watch_retries_after_failed_refresh_when_source_is_fixed() {
    let fixture = WatchFixture::new();
    let ready = fixture.source.join(".watch-ready");
    let failure = fixture.source.join(".watch-failure");

    let mut child = spawn_watch(&fixture, &ready, Some(&failure), false, &[]);
    wait_for_file_or_child_exit(&ready, &mut child);
    let session = active_try_session(&fixture.db_path).expect("active watch session");
    let first_generation = session.try_generation_id.expect("initial generation");

    fs::write(
        fixture.source.join("src/main.rs"),
        "fn main() { this is not rust }\n",
    )
    .unwrap();
    wait_for_file_or_child_exit(&failure, &mut child);
    let session = active_try_session(&fixture.db_path).expect("active watch session");
    assert_eq!(session.try_generation_id, Some(first_generation));

    fs::write(
        fixture.source.join("src/main.rs"),
        "fn main() { println!(\"fixed refresh\"); }\n",
    )
    .unwrap();
    let refreshed_generation =
        wait_for_generation_change_or_child_exit(&fixture.db_path, first_generation, &mut child);
    assert!(refreshed_generation > first_generation);

    child.kill().expect("kill watch process");
    let _ = child.wait();
    rollback(&fixture);
}

#[test]
fn try_watch_discards_cook_when_source_changes_during_build() {
    let fixture = WatchFixture::new();
    let ready = fixture.source.join(".watch-ready");
    let cook_started = fixture.source.parent().unwrap().join("watch-cook-started");
    let cook_started_env = cook_started.to_string_lossy().into_owned();
    let mut child = spawn_watch(
        &fixture,
        &ready,
        None,
        true,
        &[
            ("CONARY_TEST_TRY_WATCH_EXIT_AFTER_REFRESHES", "1"),
            ("CONARY_TEST_TRY_WATCH_PAUSE_DURING_COOK", "1"),
            (
                "CONARY_TEST_TRY_WATCH_COOK_STARTED_FILE",
                cook_started_env.as_str(),
            ),
        ],
    );
    wait_for_file_or_child_exit(&ready, &mut child);

    fs::write(
        fixture.source.join("src/main.rs"),
        "fn main() { println!(\"first refresh\"); }\n",
    )
    .unwrap();
    wait_for_file_or_child_exit(&cook_started, &mut child);
    fs::write(
        fixture.source.join("src/main.rs"),
        "fn main() { println!(\"changed during cook\"); }\n",
    )
    .unwrap();

    let output = child.wait_with_output().expect("watch output");
    assert_success(&output);
    let stdout = stdout_text(&output);
    assert!(
        stdout.lines().any(|line| {
            serde_json::from_str::<serde_json::Value>(line)
                .is_ok_and(|event| event["kind"] == "watch-refresh-skipped")
        }),
        "{}",
        output_text(&output)
    );
}

#[test]
fn try_rollback_after_failed_watch_refresh_cleans_session() {
    let fixture = WatchFixture::new();
    let ready = fixture.source.join(".watch-ready");
    let failure = fixture.source.join(".watch-failure");
    let mut child = spawn_watch(&fixture, &ready, Some(&failure), false, &[]);
    wait_for_file_or_child_exit(&ready, &mut child);

    fs::write(
        fixture.source.join("src/main.rs"),
        "fn main() { this is not rust }\n",
    )
    .unwrap();
    wait_for_file_or_child_exit(&failure, &mut child);
    child.kill().expect("kill watch process");
    let _ = child.wait();

    rollback(&fixture);
    assert!(active_try_session(&fixture.db_path).is_none());
}
